// Code generated by MockGen. DO NOT EDIT.
// Source: ./nodes/node.go

// Package nodes is a generated GoMock package.
package nodes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterfaceNode is a mock of InterfaceNode interface.
type MockInterfaceNode struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceNodeMockRecorder
}

// MockInterfaceNodeMockRecorder is the mock recorder for MockInterfaceNode.
type MockInterfaceNodeMockRecorder struct {
	mock *MockInterfaceNode
}

// NewMockInterfaceNode creates a new mock instance.
func NewMockInterfaceNode(ctrl *gomock.Controller) *MockInterfaceNode {
	mock := &MockInterfaceNode{ctrl: ctrl}
	mock.recorder = &MockInterfaceNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceNode) EXPECT() *MockInterfaceNodeMockRecorder {
	return m.recorder
}

// GetPredecessorNodes mocks base method.
func (m *MockInterfaceNode) GetPredecessorNodes(interfaceNode InterfaceNode, workflowContext *WorkflowContext) []InterfaceNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPredecessorNodes", interfaceNode, workflowContext)
	ret0, _ := ret[0].([]InterfaceNode)
	return ret0
}

// GetPredecessorNodes indicates an expected call of GetPredecessorNodes.
func (mr *MockInterfaceNodeMockRecorder) GetPredecessorNodes(interfaceNode, workflowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPredecessorNodes", reflect.TypeOf((*MockInterfaceNode)(nil).GetPredecessorNodes), interfaceNode, workflowContext)
}

// GetPredecessorNodesResults mocks base method.
func (m *MockInterfaceNode) GetPredecessorNodesResults(interfaceNode InterfaceNode, workflowContext *WorkflowContext) []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPredecessorNodesResults", interfaceNode, workflowContext)
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// GetPredecessorNodesResults indicates an expected call of GetPredecessorNodesResults.
func (mr *MockInterfaceNodeMockRecorder) GetPredecessorNodesResults(interfaceNode, workflowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPredecessorNodesResults", reflect.TypeOf((*MockInterfaceNode)(nil).GetPredecessorNodesResults), interfaceNode, workflowContext)
}

// GetResult mocks base method.
func (m *MockInterfaceNode) GetResult(interfaceNode InterfaceNode, workflowContext *WorkflowContext) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", interfaceNode, workflowContext)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetResult indicates an expected call of GetResult.
func (mr *MockInterfaceNodeMockRecorder) GetResult(interfaceNode, workflowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockInterfaceNode)(nil).GetResult), interfaceNode, workflowContext)
}

// Process mocks base method.
func (m *MockInterfaceNode) Process(interfaceNode InterfaceNode, workflowContext *WorkflowContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", interfaceNode, workflowContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockInterfaceNodeMockRecorder) Process(interfaceNode, workflowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockInterfaceNode)(nil).Process), interfaceNode, workflowContext)
}

// ProcessVirt mocks base method.
func (m *MockInterfaceNode) ProcessVirt(workflowContext *WorkflowContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessVirt", workflowContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessVirt indicates an expected call of ProcessVirt.
func (mr *MockInterfaceNodeMockRecorder) ProcessVirt(workflowContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessVirt", reflect.TypeOf((*MockInterfaceNode)(nil).ProcessVirt), workflowContext)
}

// SaveResult mocks base method.
func (m *MockInterfaceNode) SaveResult(interfaceNode InterfaceNode, workflowContext *WorkflowContext, result interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveResult", interfaceNode, workflowContext, result)
}

// SaveResult indicates an expected call of SaveResult.
func (mr *MockInterfaceNodeMockRecorder) SaveResult(interfaceNode, workflowContext, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResult", reflect.TypeOf((*MockInterfaceNode)(nil).SaveResult), interfaceNode, workflowContext, result)
}
